#ifndef CMAKE_DEFINES_HPP
#define CMAKE_DEFINES_HPP

#define PROJECT_NAME "@PROJECT_NAME@"
#define PROJECT_VERSION "@PROJECT_VERSION@"
#define COPYRIGHT_NOTICE "@PROJECT_COPYRIGHT@"

#endif//CMAKE_DEFINES_HPP