#ifndef CORE__EXCEPTIONS__UNRECOGNIZED_CELL_VALUE_ERROR
#define CORE__EXCEPTIONS__UNRECOGNIZED_CELL_VALUE_ERROR

#include "../../make_basic_exception.hpp"

namespace Picross
{
    DECLARE_BASIC_EXCEPTION(UnrecognizedCellValueError)
}

#endif//CORE__EXCEPTIONS__UNRECOGNIZED_CELL_VALUE_ERROR